name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'

    steps:
      - uses: actions/checkout@v4

      # Install Rust (stable)
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      # Cache cargo artifacts
      - uses: Swatinem/rust-cache@v2

      - uses: jetli/trunk-action@v0.5.1
        with:
          version: 'latest'

      # Build with trunk
      - name: Build
        run: |
          cd ./super-trader
          trunk build --release

      # Deploy dist/ to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./super-trader/dist
